'use client'

import { useMemo, useState } from 'react'
import { AlertCircle, ArrowRight, Check, CheckCircle2, Clipboard, Download, FileText, Info, Loader2, Mail, Paperclip, Pencil, Plus, RefreshCcw, ShieldCheck, Upload, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { DEMO_RFQ_INPUT } from '@/lib/demo-data'
import { RFQ, RFQFieldProvenance } from '@/lib/rfq-schema'
import { formatFieldValue, getFieldDisplayName, validateRFQ } from '@/lib/validate-rfq'

const inputFields = [
  ['customer_company', 'Customer company'], ['contact_name', 'Contact name'], ['contact_email', 'Contact email'], ['subject', 'Subject'],
  ['product_type', 'Product type'], ['application', 'Application'], ['quantity', 'Quantity'], ['requested_delivery', 'Requested delivery'],
  ['cable_length', 'Cable length'], ['cable_color', 'Cable color'], ['connector_family', 'Connector family'], ['connector_part_number', 'Connector part number'],
  ['wire_gauge', 'Wire gauge'], ['voltage_rating', 'Voltage rating'], ['current_rating', 'Current rating'], ['material', 'Material'],
  ['rohs', 'RoHS compliance'], ['packaging_requirements', 'Packaging requirements'],
] as const

const sections = [
  { title: 'Customer & request', fields: inputFields.slice(0, 4) },
  { title: 'Product & commercial', fields: inputFields.slice(4, 8) },
  { title: 'Technical requirements', fields: inputFields.slice(8, 16) },
  { title: 'Compliance & packaging', fields: inputFields.slice(16) },
]

export default function RFQDashboard() {
  const [rfq, setRfq] = useState<RFQ | null>(null)
  const [originalRfq, setOriginalRfq] = useState<RFQ | null>(null)
  const [source, setSource] = useState('')
  const [isExtracting, setIsExtracting] = useState(false)
  const [demo, setDemo] = useState(false)
  const [activeTab, setActiveTab] = useState<'overview' | 'review' | 'handoff'>('overview')
  const [reviewerNotes, setReviewerNotes] = useState('')
  const [draftCopied, setDraftCopied] = useState(false)
  const [showArchitecture, setShowArchitecture] = useState(false)
  const validation = useMemo(() => rfq ? validateRFQ(rfq) : null, [rfq])

  async function processRFQ(useDemo = false) {
    setIsExtracting(true)
    try {
      const response = await fetch('/api/extract-rfq', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: useDemo ? DEMO_RFQ_INPUT : source, use_demo: useDemo }) })
      const data = await response.json()
      if (data.success) {
        setRfq(data.rfq)
        setOriginalRfq(data.rfq)
        setDemo(data.demo === true)
        if (useDemo) setSource(DEMO_RFQ_INPUT)
      } else {
        window.alert(data.error || 'RFQ extraction failed.')
      }
    } finally { setIsExtracting(false) }
  }

  function reset() { setRfq(null); setOriginalRfq(null); setSource(''); setActiveTab('overview'); setReviewerNotes('') }
  function updateField(field: string, value: string) { if (!rfq) return; setRfq({ ...rfq, [field]: value || null }) }
  function exportJSON() { if (!rfq) return; const blob = new Blob([JSON.stringify({ ...rfq, validation, reviewer_notes: reviewerNotes }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${rfq.rfq_id}.json`; link.click(); URL.revokeObjectURL(url) }
  function copyDraft() { navigator.clipboard.writeText(clarificationDraft); setDraftCopied(true); setTimeout(() => setDraftCopied(false), 1600) }

  const missingLabels = validation?.missing_fields.map(getFieldDisplayName) ?? []
  const clarificationDraft = rfq ? `Subject: Additional information required for RFQ\n\nHello ${rfq.contact_name || 'there'},\n\nThank you for your inquiry regarding the ${rfq.product_type?.toLowerCase() || 'requested product'}.\n\nThe following mandatory fields are still required for technical review:\n\n${missingLabels.map((label) => `- ${label.toLowerCase()}`).join('\n') || '- None'}\n\nAdvisory details (helpful but not required to begin review) may include connector part numbers, material, tolerance, finish or plating, annual volume, target price, and other standards. Please provide any available advisory details without inferring values.\n\nOnce the mandatory details are available, the request can proceed to technical review.\n\nBest regards,\nSales / Engineering Team` : ''

  return <main className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border/70 bg-background/95 backdrop-blur">
      <div className="mx-auto flex max-w-[1440px] items-center justify-between gap-4 px-4 py-4 lg:px-8">
        <div className="flex min-w-0 items-center gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary text-primary-foreground"><ShieldCheck /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="truncate text-sm font-semibold tracking-tight sm:text-base">Manufacturing RFQ Assistant</h1><span className="rounded-full border border-blue-400/30 bg-blue-400/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-blue-300">Demo / Synthetic Data</span></div><p className="hidden text-xs text-muted-foreground sm:block">Turn unstructured customer requests into review-ready RFQs.</p></div></div>
        <div className="flex shrink-0 items-center gap-2"><Button variant="ghost" size="sm" onClick={() => setShowArchitecture(true)}><Info data-icon="inline-start" /> <span className="hidden sm:inline">How it works</span></Button><Button variant="outline" size="sm" onClick={reset}><Plus data-icon="inline-start" /> New RFQ</Button></div>
      </div>
    </header>

    <div className="mx-auto max-w-[1440px] px-4 py-6 lg:px-8">
      <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-medium uppercase tracking-[0.2em] text-blue-300">RFQ WORKSPACE / {rfq?.rfq_id || 'NEW INTAKE'}</p><h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">Structure the request. Review the gaps.</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">AI interprets incoming customer information. Deterministic checks keep the review explainable and human-approved.</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-emerald-400" /> System ready</div></div>
      <WorkflowProgress active={rfq ? activeTab === 'handoff' ? 5 : activeTab === 'review' ? 4 : 3 : 1} />

      {!rfq ? <Intake source={source} setSource={setSource} isExtracting={isExtracting} onDemo={() => processRFQ(true)} onProcess={() => processRFQ(false)} /> : <>
        <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card/50 px-4 py-3"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-lg bg-blue-400/10 text-blue-300"><CheckCircle2 /></div><div><p className="text-sm font-medium">{demo ? 'Demo extraction — synthetic predefined result.' : 'Live extraction complete.'}</p><p className="text-xs text-muted-foreground">Original customer request preserved for review.</p></div></div><div className="flex gap-2"><Button variant={activeTab === 'overview' ? 'secondary' : 'ghost'} size="sm" onClick={() => setActiveTab('overview')}>RFQ record</Button><Button variant={activeTab === 'review' ? 'secondary' : 'ghost'} size="sm" onClick={() => setActiveTab('review')}><Pencil data-icon="inline-start" /> Review</Button><Button variant={activeTab === 'handoff' ? 'secondary' : 'ghost'} size="sm" onClick={() => setActiveTab('handoff')}><ArrowRight data-icon="inline-start" /> Handoff</Button></div></div>
        {activeTab === 'overview' && <Overview source={source || DEMO_RFQ_INPUT} rfq={rfq} validation={validation!} missingLabels={missingLabels} onReview={() => setActiveTab('review')} />}
        {activeTab === 'review' && <Review rfq={rfq} originalRfq={originalRfq!} updateField={updateField} reviewerNotes={reviewerNotes} setReviewerNotes={setReviewerNotes} />}
        {activeTab === 'handoff' && <Handoff rfq={rfq} validation={validation!} reviewerNotes={reviewerNotes} onExport={exportJSON} />}
      </>}
    </div>
    <footer className="mx-auto flex max-w-[1440px] flex-col gap-2 border-t border-border/60 px-4 py-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>Portfolio demonstration — synthetic data only.</span><span>Human review required before any engineering or commercial action.</span></footer>
    {showArchitecture && <ArchitectureModal onClose={() => setShowArchitecture(false)} />}
  </main>
}

function WorkflowProgress({ active }: { active: number }) { const steps = ['Intake', 'Extract', 'Validate', 'Review', 'Handoff']; return <div className="mb-6 flex items-center overflow-x-auto rounded-xl border border-border bg-card/40 px-4 py-3">{steps.map((step, index) => <div key={step} className="flex min-w-[92px] flex-1 items-center last:flex-none"><div className="flex items-center gap-2"><span className={`flex size-6 items-center justify-center rounded-full text-[11px] font-semibold ${index + 1 <= active ? 'bg-blue-400 text-slate-950' : 'bg-muted text-muted-foreground'}`}>{index + 1 < active ? <Check /> : index + 1}</span><span className={`text-xs font-medium ${index + 1 <= active ? 'text-foreground' : 'text-muted-foreground'}`}>{step}</span></div>{index < steps.length - 1 && <div className={`mx-3 h-px flex-1 ${index + 1 < active ? 'bg-blue-400/70' : 'bg-border'}`} />}</div>)}</div> }

function Intake({ source, setSource, isExtracting, onDemo, onProcess }: any) { return <div className="grid gap-5 lg:grid-cols-[1fr_0.72fr]"><section className="rounded-xl border border-border bg-card/60"><div className="border-b border-border px-5 py-4"><div className="flex items-center gap-2"><Mail className="text-blue-300" /><h3 className="font-semibold">Customer request intake</h3></div><p className="mt-1 text-xs text-muted-foreground">Paste an email or upload a supported source document.</p></div><div className="flex flex-col gap-4 p-5"><textarea value={source} onChange={e => setSource(e.target.value)} placeholder="Paste customer email or RFQ text here..." className="min-h-64 resize-y rounded-lg border border-input bg-background/60 p-4 text-sm leading-6 outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring" aria-label="Customer request text" /><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Button variant="secondary" onClick={onDemo}><RefreshCcw data-icon="inline-start" /> Load sample RFQ</Button><Button variant="outline" disabled><Upload data-icon="inline-start" /> Upload file</Button></div><Button onClick={onProcess} disabled={!source.trim() || isExtracting}>{isExtracting ? <><Loader2 className="animate-spin" data-icon="inline-start" /> Extracting...</> : <>Process request <ArrowRight data-icon="inline-end" /></>}</Button></div><p className="text-[11px] text-muted-foreground">Supported: pasted text, PDF, PNG, JPG/JPEG. Engineering geometry is not inspected in this demo.</p></div></section><aside className="flex flex-col gap-4"><div className="rounded-xl border border-border bg-card/60 p-5"><p className="mb-3 text-xs font-medium uppercase tracking-wider text-muted-foreground">Workflow principle</p><div className="flex flex-col gap-3 text-sm"><FlowLine icon={<FileText />} label="Unstructured request" /><FlowLine icon={<ArrowRight />} label="AI extraction" /><FlowLine icon={<CheckCircle2 />} label="Typed RFQ schema" /><FlowLine icon={<ShieldCheck />} label="Deterministic validation" /><FlowLine icon={<Pencil />} label="Human review" /></div></div><div className="rounded-xl border border-blue-400/20 bg-blue-400/5 p-5"><p className="text-sm font-medium text-blue-200">Demo mode is ready</p><p className="mt-1 text-xs leading-5 text-muted-foreground">No API key is required. The sample returns a predefined, synthetic extraction so the whole workflow can be explored safely.</p></div></aside></div> }
function FlowLine({ icon, label }: any) { return <div className="flex items-center gap-3"><span className="text-blue-300">{icon}</span><span>{label}</span></div> }

// @ts-expect-error RFQ attachment metadata is rendered separately from schema field controls.
function Overview({ source, rfq, validation, missingLabels, onReview }: any) { return <div className="grid gap-5 xl:grid-cols-[0.82fr_1.18fr]"><section className="rounded-xl border border-border bg-card/60"><div className="border-b border-border px-5 py-4"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Source request</p><h3 className="mt-1 font-semibold">Customer email / attachments</h3></div><span className="rounded-full border border-border px-2 py-1 text-[10px] text-muted-foreground">Read only</span></div></div><div className="p-5"><pre className="max-h-[620px] whitespace-pre-wrap font-mono text-xs leading-6 text-muted-foreground">{source}</pre><div className="mt-5 border-t border-border pt-4"><p className="mb-3 text-xs font-medium uppercase tracking-wider text-muted-foreground">Attachments</p>{rfq.attachments.length ? rfq.attachments.map((attachment: any) => <div key={attachment.filename} className="flex items-center gap-3 rounded-lg border border-border bg-background/40 p-3"><FileText className="text-blue-300" /><div className="min-w-0 flex-1"><p className="truncate text-sm">{attachment.filename}</p><p className="text-xs text-muted-foreground">{attachment.type.toUpperCase()} · present · geometry not inspected</p></div><Paperclip className="text-muted-foreground" /></div>) : <p className="text-sm text-muted-foreground">No file uploaded or attached.</p>}</div></div></section><section className="flex flex-col gap-5"><div className="rounded-xl border border-border bg-card/60"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Structured RFQ</p><h3 className="mt-1 font-semibold">{rfq.rfq_id}</h3></div><div className="flex items-center gap-2"><span className="rounded-full border border-amber-400/30 bg-amber-400/10 px-2.5 py-1 text-xs font-medium text-amber-200">{validation.required_fields_met} / {validation.total_required_fields} required areas</span><Button size="sm" onClick={onReview}><Pencil data-icon="inline-start" /> Review RFQ</Button></div></div><div className="grid gap-5 p-5 sm:grid-cols-2">{sections.map(section => <div key={section.title}><p className="mb-3 text-xs font-medium uppercase tracking-wider text-muted-foreground">{section.title}</p><div className="flex flex-col gap-2">{section.fields.map(([field, label]) => <RFQField key={field} label={label} value={rfq[field]} source={rfq[field] ? field === 'quantity' || field === 'cable_length' ? 'customer email' : field === 'attachments' ? 'attachment list' : 'customer email' : undefined} />)}</div></div>)}</div></div><div className="grid gap-5 md:grid-cols-2"><Completeness validation={validation} /><MissingPanel missingLabels={missingLabels} /></div><ClarificationDraft draft={clarificationDraftFor(rfq, missingLabels)} /></section></div> }
function clarificationDraftFor(rfq: RFQ, labels: string[]) { return `Subject: Additional information required for RFQ\n\nHello ${rfq.contact_name || 'there'},\n\nThank you for your inquiry regarding the ${rfq.product_type?.toLowerCase() || 'requested product'}.\n\nMandatory fields still required for technical review:\n\n${labels.map(label => `- ${label.toLowerCase()}`).join('\n') || '- None'}\n\nAdvisory fields are helpful but not required to begin review: connector part number, material, tolerance, finish or plating, annual volume, target price, and other standards. Please provide any available advisory details without inferring values.\n\nOnce the mandatory details are available, the request can proceed to technical review.\n\nBest regards,\nSales / Engineering Team` }
function RFQField({ label, value, source }: any) { return <div className="rounded-lg border border-border/70 bg-background/30 px-3 py-2.5"><div className="flex items-start justify-between gap-2"><span className="text-xs text-muted-foreground">{label}</span>{value ? <span className="rounded px-1.5 py-0.5 text-[10px] text-blue-300">{source}</span> : <span className="text-[10px] text-amber-300">Missing</span>}</div><p className={`mt-1 text-sm ${value ? 'text-foreground' : 'text-muted-foreground'}`}>{formatFieldValue(value)}</p></div> }
function Completeness({ validation }: any) { return <div className="rounded-xl border border-border bg-card/60 p-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">RFQ completeness</p><p className="mt-2 text-3xl font-semibold">{validation.completeness_percentage}<span className="text-base text-muted-foreground">%</span></p></div><AlertCircle className="text-amber-300" /></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-amber-300" style={{ width: `${validation.completeness_percentage}%` }} /></div><p className="mt-3 text-xs text-muted-foreground">Calculated by deterministic required-field checks, not by the model.</p></div> }
function MissingPanel({ missingLabels }: any) { return <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-5"><p className="text-xs uppercase tracking-wider text-amber-200">Needs clarification</p><div className="mt-3 flex flex-col gap-2">{missingLabels.map((label: string) => <div key={label} className="flex items-center gap-2 text-sm"><X className="text-amber-300" />{label}</div>)}</div></div> }
function ClarificationDraft({ draft }: { draft: string }) { const [copied, setCopied] = useState(false); return <div className="rounded-xl border border-border bg-card/60"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Clarification draft</p><h3 className="mt-1 font-semibold">Draft only — human approval required</h3></div><Button variant="outline" size="sm" onClick={() => { navigator.clipboard.writeText(draft); setCopied(true); setTimeout(() => setCopied(false), 1200) }}>{copied ? <Check data-icon="inline-start" /> : <Clipboard data-icon="inline-start" />}{copied ? 'Copied' : 'Copy draft'}</Button></div><pre className="whitespace-pre-wrap p-5 text-sm leading-6 text-muted-foreground">{draft}</pre></div> }

function Review({ rfq, originalRfq, updateField, reviewerNotes, setReviewerNotes }: any) { return <div className="grid gap-5 xl:grid-cols-[1fr_0.72fr]"><section className="rounded-xl border border-border bg-card/60"><div className="border-b border-border px-5 py-4"><p className="text-xs uppercase tracking-wider text-muted-foreground">Human review</p><h3 className="mt-1 font-semibold">Confirm or correct extracted values</h3><p className="mt-1 text-xs text-muted-foreground">Edits are kept separate from the original extraction until reviewed.</p></div><div className="grid gap-4 p-5 sm:grid-cols-2">{inputFields.map(([field, label]) => <label key={field} className="flex flex-col gap-2"><span className="flex items-center justify-between text-xs text-muted-foreground"><span>{label}</span><span className={rfq[field] !== originalRfq[field] ? 'text-blue-300' : 'text-muted-foreground'}>{rfq[field] !== originalRfq[field] ? 'Human edited' : rfq[field] ? 'AI extracted' : 'Missing'}</span></span><input value={rfq[field] ?? ''} onChange={e => updateField(field, e.target.value)} placeholder="Not provided" className="h-9 rounded-lg border border-input bg-background/50 px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label>)}</div></section><aside className="flex flex-col gap-5"><div className="rounded-xl border border-border bg-card/60 p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">Reviewer notes</p><textarea value={reviewerNotes} onChange={e => setReviewerNotes(e.target.value)} placeholder="Add context for the next reviewer..." className="mt-3 min-h-32 w-full resize-y rounded-lg border border-input bg-background/50 p-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /></div><div className="rounded-xl border border-blue-400/20 bg-blue-400/5 p-5"><p className="text-sm font-medium text-blue-200">Review guidance</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Confirm every required field before handoff. A human correction never silently replaces the source value; it is labeled as reviewed input.</p></div></aside></div> }
function Handoff({ rfq, validation, reviewerNotes, onExport }: any) { const ready = validation.missing_fields.length === 0; return <div className="mx-auto max-w-4xl rounded-xl border border-border bg-card/60"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-border px-5 py-5"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">RFQ handoff</p><h3 className="mt-1 text-xl font-semibold">{rfq.rfq_id}</h3></div><div className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${ready ? 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200' : 'border-amber-400/30 bg-amber-400/10 text-amber-200'}`}>{ready ? 'READY FOR ENGINEERING REVIEW' : 'NOT READY FOR ENGINEERING'}</div></div><div className="grid gap-x-8 gap-y-6 p-5 sm:grid-cols-2"><HandoffItem label="Customer" value={rfq.customer_company} /><HandoffItem label="Contact" value={rfq.contact_name && rfq.contact_email ? `${rfq.contact_name} · ${rfq.contact_email}` : rfq.contact_name || rfq.contact_email} /><HandoffItem label="Requested delivery" value={rfq.requested_delivery} /><HandoffItem label="Product" value={rfq.product_type} /><HandoffItem label="Quantity" value={rfq.quantity ? `${rfq.quantity.toLocaleString()} pcs` : null} /><HandoffItem label="Application" value={rfq.application} /><HandoffItem label="Technical specifications" value={[rfq.cable_length && `Length: ${rfq.cable_length}`, rfq.cable_color && `Color: ${rfq.cable_color}`, rfq.connector_family && `Connector: ${rfq.connector_family}`, rfq.wire_gauge && `Gauge: ${rfq.wire_gauge}`, rfq.voltage_rating && `Voltage: ${rfq.voltage_rating}`, rfq.current_rating && `Current: ${rfq.current_rating}`].filter(Boolean).join(' · ') || null} /><HandoffItem label="Compliance requirements" value={rfq.rohs || rfq.reach || rfq.ul} /><HandoffItem label="Missing / unresolved" value={validation.missing_fields.map(getFieldDisplayName).join(', ') || 'None'} /><HandoffItem label="Attachments" value={rfq.attachments.map((a: any) => a.filename).join(', ')} /><HandoffItem label="Reviewer notes" value={reviewerNotes} /></div><div className="flex flex-wrap justify-end gap-2 border-t border-border px-5 py-4"><Button variant="outline" onClick={onExport}><Download data-icon="inline-start" /> Export JSON</Button></div></div> }
function HandoffItem({ label, value }: any) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm">{formatFieldValue(value)}</p></div> }
function ArchitectureModal({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-labelledby="architecture-title" onClick={onClose}><div className="w-full max-w-lg rounded-xl border border-border bg-card p-6 shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-blue-300">System architecture</p><h3 id="architecture-title" className="mt-1 text-lg font-semibold">Explainable by design</h3></div><Button variant="ghost" size="icon-sm" onClick={onClose} aria-label="Close"><X /></Button></div><div className="my-6 flex flex-col items-center gap-2 text-sm">{['Unstructured Request', 'AI Extraction', 'Typed RFQ Schema', 'Deterministic Validation', 'Human Review', 'Trusted Handoff'].map((step, i) => <div key={step} className="flex flex-col items-center gap-2"><div className="rounded-lg border border-border bg-background/60 px-4 py-2 font-medium">{step}</div>{i < 5 && <ArrowRight className="rotate-90 text-blue-300" />}</div>)}</div><p className="text-sm leading-6 text-muted-foreground">The language model interprets unstructured information. Required-field checks, workflow status, and readiness decisions are handled deterministically in software.</p></div></div> }

const clarificationDraft = ''

